# Weeder configuration file
# https://github.com/ndmitchell/weeder
##########################

# There are lots of internals of Rattle want to test, but don't want to expose
- message: Module reused between components

# Module still in development
- message:
  - name: Weeds exported
  - module: Development.Rattle.Profile
