# Can't use GHC 8.8.1 because of https://gitlab.haskell.org/ghc/ghc/issues/17575
resolver: lts-14.17
packages:
- .

extra-deps:
  - git: https://github.com/ndmitchell/shake.git
    commit: a322c0c1b793dbe4c822276708aee40ef5a73bd0
  - extra-1.6.20
